// noinspection SpellCheckingInspection

import { prisma } from "../db/index.js";

const CITY_SEED = [
    "Helsinki",
    "Tampere",
    "Espoo",
    "Vantaa",
    "Turku",
    "Oulu",
    "Lahti",
    "Kuopio",
    "Jyvaeskylae",
    "Pori",
    "Lappeenranta",
    "Vaasa",
    "Kotka",
    "Joensuu",
    "Haemeenlinna",
    "Porvoo",
    "Mikkeli",
    "Hyvinge",
    "Jaervenpaeae",
    "Nurmijaervi",
    "Rauma",
    "Mellunkylae",
    "Lohja",
    "Vuosaari",
    "Kokkola",
    "Kajaani",
    "Rovaniemi",
    "Tuusula",
    "Kirkkonummi",
    "Seinaejoki",
    "Kerava",
    "Kouvola",
    "Imatra",
    "Nokia",
    "Savonlinna",
    "Kallio",
    "Riihimaeki",
    "Kaarela",
    "Vihti",
    "Salo",
    "Kangasala",
    "Raisio",
    "Karhula",
    "Kemi",
    "Iisalmi",
    "Varkaus",
    "Raahe",
    "Yloejaervi",
    "Hamina",
    "Kaarina",
    "Tornio",
    "Heinola",
    "Hollola",
    "Valkeakoski",
    "Siilinjaervi",
    "Lauttasaari",
    "Sibbo",
    "Jakobstad",
    "Lempaeaelae",
    "Maentsaelae",
    "Forssa",
    "Kuusamo",
    "Munkkiniemi",
    "Haukipudas",
    "Korsholm",
    "Laukaa",
    "Anjala",
    "Uusikaupunki",
    "Janakkala",
    "Pirkkala",
    "Laensi-Turunmaa",
    "Lovisa",
    "Jaemsae",
    "Lieto",
    "Vammala",
    "Nastola",
    "Orimattila",
    "Kauhajoki",
    "Ekenaes",
    "Kempele",
    "Lapua",
    "Lieksa",
    "Naantali",
    "AEaenekoski",
    "Ylivieska",
    "Kontiolahti",
    "Kankaanpaeae",
    "Ulvila",
    "Pieksaemaeki",
    "Kiiminki",
    "Pargas",
    "Nurmo",
    "Ilmajoki",
    "Liperi",
    "Keuruu",
    "Leppaevirta",
    "Kurikka",
    "Nivala",
    "Joutseno",
    "Pedersoere",
    "Sotkamo",
    "AElajaervi",
    "Kuhmo",
    "Paimio",
    "Saarijaervi"
];

export const seedCities = async () => {
    for (const cityName of CITY_SEED) {
        await prisma.city.upsert({
            where: { name: cityName },
            update: {},
            create: { name: cityName }
        });
    }
};
//todo: transfer to repo layer